/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardMembersRouteImport } from './routes/dashboard.members'
import { Route as DashboardCheckinRouteImport } from './routes/dashboard.checkin'
import { Route as AdminBirthdaysRouteImport } from './routes/admin.birthdays'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as DashboardScheduleIndexRouteImport } from './routes/dashboard.schedule.index'
import { Route as DashboardScheduleIdRouteImport } from './routes/dashboard.schedule.$id'
import { Route as AdminScheduleIdIndexRouteImport } from './routes/admin.schedule.$id.index'
import { Route as ApiPublicHooksSendPushRouteImport } from './routes/api/public/hooks/send-push'
import { Route as AdminScheduleIdResponsesRouteImport } from './routes/admin.schedule.$id.responses'
import { Route as AdminScheduleIdCheckinRouteImport } from './routes/admin.schedule.$id.checkin'

const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMembersRoute = DashboardMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCheckinRoute = DashboardCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminBirthdaysRoute = AdminBirthdaysRouteImport.update({
  id: '/birthdays',
  path: '/birthdays',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardScheduleIndexRoute = DashboardScheduleIndexRouteImport.update({
  id: '/schedule/',
  path: '/schedule/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardScheduleIdRoute = DashboardScheduleIdRouteImport.update({
  id: '/schedule/$id',
  path: '/schedule/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminScheduleIdIndexRoute = AdminScheduleIdIndexRouteImport.update({
  id: '/schedule/$id/',
  path: '/schedule/$id/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicHooksSendPushRoute = ApiPublicHooksSendPushRouteImport.update({
  id: '/api/public/hooks/send-push',
  path: '/api/public/hooks/send-push',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminScheduleIdResponsesRoute =
  AdminScheduleIdResponsesRouteImport.update({
    id: '/schedule/$id/responses',
    path: '/schedule/$id/responses',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminScheduleIdCheckinRoute = AdminScheduleIdCheckinRouteImport.update({
  id: '/schedule/$id/checkin',
  path: '/schedule/$id/checkin',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/pending': typeof PendingRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/birthdays': typeof AdminBirthdaysRoute
  '/dashboard/checkin': typeof DashboardCheckinRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/schedule/$id': typeof DashboardScheduleIdRoute
  '/dashboard/schedule/': typeof DashboardScheduleIndexRoute
  '/admin/schedule/$id/checkin': typeof AdminScheduleIdCheckinRoute
  '/admin/schedule/$id/responses': typeof AdminScheduleIdResponsesRoute
  '/api/public/hooks/send-push': typeof ApiPublicHooksSendPushRoute
  '/admin/schedule/$id/': typeof AdminScheduleIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pending': typeof PendingRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/birthdays': typeof AdminBirthdaysRoute
  '/dashboard/checkin': typeof DashboardCheckinRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/schedule/$id': typeof DashboardScheduleIdRoute
  '/dashboard/schedule': typeof DashboardScheduleIndexRoute
  '/admin/schedule/$id/checkin': typeof AdminScheduleIdCheckinRoute
  '/admin/schedule/$id/responses': typeof AdminScheduleIdResponsesRoute
  '/api/public/hooks/send-push': typeof ApiPublicHooksSendPushRoute
  '/admin/schedule/$id': typeof AdminScheduleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/pending': typeof PendingRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/birthdays': typeof AdminBirthdaysRoute
  '/dashboard/checkin': typeof DashboardCheckinRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/schedule/$id': typeof DashboardScheduleIdRoute
  '/dashboard/schedule/': typeof DashboardScheduleIndexRoute
  '/admin/schedule/$id/checkin': typeof AdminScheduleIdCheckinRoute
  '/admin/schedule/$id/responses': typeof AdminScheduleIdResponsesRoute
  '/api/public/hooks/send-push': typeof ApiPublicHooksSendPushRoute
  '/admin/schedule/$id/': typeof AdminScheduleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/pending'
    | '/admin/announcements'
    | '/admin/birthdays'
    | '/dashboard/checkin'
    | '/dashboard/members'
    | '/dashboard/profile'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/schedule/$id'
    | '/dashboard/schedule/'
    | '/admin/schedule/$id/checkin'
    | '/admin/schedule/$id/responses'
    | '/api/public/hooks/send-push'
    | '/admin/schedule/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pending'
    | '/admin/announcements'
    | '/admin/birthdays'
    | '/dashboard/checkin'
    | '/dashboard/members'
    | '/dashboard/profile'
    | '/admin'
    | '/dashboard'
    | '/dashboard/schedule/$id'
    | '/dashboard/schedule'
    | '/admin/schedule/$id/checkin'
    | '/admin/schedule/$id/responses'
    | '/api/public/hooks/send-push'
    | '/admin/schedule/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/pending'
    | '/admin/announcements'
    | '/admin/birthdays'
    | '/dashboard/checkin'
    | '/dashboard/members'
    | '/dashboard/profile'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/schedule/$id'
    | '/dashboard/schedule/'
    | '/admin/schedule/$id/checkin'
    | '/admin/schedule/$id/responses'
    | '/api/public/hooks/send-push'
    | '/admin/schedule/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  PendingRoute: typeof PendingRoute
  ApiPublicHooksSendPushRoute: typeof ApiPublicHooksSendPushRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/members': {
      id: '/dashboard/members'
      path: '/members'
      fullPath: '/dashboard/members'
      preLoaderRoute: typeof DashboardMembersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/checkin': {
      id: '/dashboard/checkin'
      path: '/checkin'
      fullPath: '/dashboard/checkin'
      preLoaderRoute: typeof DashboardCheckinRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/birthdays': {
      id: '/admin/birthdays'
      path: '/birthdays'
      fullPath: '/admin/birthdays'
      preLoaderRoute: typeof AdminBirthdaysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/schedule/': {
      id: '/dashboard/schedule/'
      path: '/schedule'
      fullPath: '/dashboard/schedule/'
      preLoaderRoute: typeof DashboardScheduleIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/schedule/$id': {
      id: '/dashboard/schedule/$id'
      path: '/schedule/$id'
      fullPath: '/dashboard/schedule/$id'
      preLoaderRoute: typeof DashboardScheduleIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/schedule/$id/': {
      id: '/admin/schedule/$id/'
      path: '/schedule/$id'
      fullPath: '/admin/schedule/$id/'
      preLoaderRoute: typeof AdminScheduleIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/hooks/send-push': {
      id: '/api/public/hooks/send-push'
      path: '/api/public/hooks/send-push'
      fullPath: '/api/public/hooks/send-push'
      preLoaderRoute: typeof ApiPublicHooksSendPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/schedule/$id/responses': {
      id: '/admin/schedule/$id/responses'
      path: '/schedule/$id/responses'
      fullPath: '/admin/schedule/$id/responses'
      preLoaderRoute: typeof AdminScheduleIdResponsesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schedule/$id/checkin': {
      id: '/admin/schedule/$id/checkin'
      path: '/schedule/$id/checkin'
      fullPath: '/admin/schedule/$id/checkin'
      preLoaderRoute: typeof AdminScheduleIdCheckinRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminBirthdaysRoute: typeof AdminBirthdaysRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminScheduleIdCheckinRoute: typeof AdminScheduleIdCheckinRoute
  AdminScheduleIdResponsesRoute: typeof AdminScheduleIdResponsesRoute
  AdminScheduleIdIndexRoute: typeof AdminScheduleIdIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminBirthdaysRoute: AdminBirthdaysRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminScheduleIdCheckinRoute: AdminScheduleIdCheckinRoute,
  AdminScheduleIdResponsesRoute: AdminScheduleIdResponsesRoute,
  AdminScheduleIdIndexRoute: AdminScheduleIdIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardCheckinRoute: typeof DashboardCheckinRoute
  DashboardMembersRoute: typeof DashboardMembersRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardScheduleIdRoute: typeof DashboardScheduleIdRoute
  DashboardScheduleIndexRoute: typeof DashboardScheduleIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCheckinRoute: DashboardCheckinRoute,
  DashboardMembersRoute: DashboardMembersRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardScheduleIdRoute: DashboardScheduleIdRoute,
  DashboardScheduleIndexRoute: DashboardScheduleIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  PendingRoute: PendingRoute,
  ApiPublicHooksSendPushRoute: ApiPublicHooksSendPushRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
